#!/bin/bash

set -eu

component=$1
sed -i -e "s|imagePullPolicy: Always|imagePullPolicy: IfNotPresent|g" ~/workspace/eirini-release/deploy/**/*.yml
sed -i -e "s|image: eirini/$component.*$|image: eirini/$component|g" ~/workspace/eirini-release/deploy/**/*.yml

docker build . --file docker/$component/Dockerfile --build-arg GIT_SHA=$(git rev-parse HEAD)-dirty --tag $IMAGE
